{
 "title": "Braxen",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Current production",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  e_pv\nFROM braxen_fronius\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Production",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  e_year AS \"Yearly production\"\nFROM braxen_fronius\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  e_total AS \"Total production\"\nFROM braxen_fronius\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  e_day AS \"Today\"\nFROM braxen_fronius\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "AC power",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  e_pv AS \"Power\"\nFROM braxen_fronius\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Accumulated daily",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  e_day AS \"Daily production\"\nFROM braxen_fronius\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Yearly accumulation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",24h),\n  sum(max(e_day)) OVER (ORDER BY $__timeGroup(\"time\",24h)) AS \"Production\"\nFROM braxen_fronius\nWHERE\n  $__timeFilter(\"time\")\nGROUP BY 1\nORDER BY 1"
    }
   ]
  }
 ]
}